---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
    - role: finaldes.ansible_nginx
      become: true
      stable: true
  # tasks:
  #   - name: "Include ansible-nginx"
  #     include_role:
  #       name: "ansible-nginx"
